### ISSUE TITLE
сервер упал

### ISSUE THREAD

**Issue by officialdakari** [hatedestiny6/zephyr#3]
сервер упал

**Comment by synxur2f** [comment]
пытаюсь подружиться с другим хостингом

**Comment by synxur2f** [comment]
пытался подружиться с railway, vercel, render. последний жутко виснет. в итоге залил на glitch.

**Comment by officialdakari** [comment]
я могу тебе захостить на своём VDS, надо? будет ещё домен

**Comment by synxur2f** [comment]
за сколько ?

> я могу тебе захостить на своём VDS, надо? будет ещё домен
